version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
      - ls
      - pwd
      - ls
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: src
